name: muteable_notifiers
description: Implementations of ChangeNotifier and ValueNotifier that can be muted for single/multiple calls.
version: 1.0.6
homepage: https://github.com/dzliergaard/mutable_notifier

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
